server:
  port: 8083
spring:
  cloud:
    config:
      server:
        git:
          uri: git@github.com:jcatom/spring_cloud_template_config.git
          search-paths: /**
          default-label: dev
          basedir: config/target
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
